/* Generated by Yosys 0.50+56 (git sha1 78960292d, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "./verilog/map_table.sv:2.1-66.10" *)
module map_table(clock, reset, dispatch_en_1, dispatch_en_2, CDB_valid_1, CDB_valid_2, if_branch_1, if_branch_2, br_stk_idx_copy_mt, br_copy_valid, br_stk_idx_recover_mt, br_recover_valid, mt_inst1_rs1, mt_inst1_src2, mt_inst2_rs1, mt_inst2_rs2, mt_inst1_rd, mt_inst2_rd, mt_inst1_dest_tag, mt_inst2_dest_tag, CDB_tag_1
, CDB_tag_2, mt_inst1_src_tag_plus_1, mt_inst1_src_tag_plus_2, mt_inst2_src_tag_plus_1, mt_inst2_src_tag_plus_2, mt_inst1_dest_tag_out, mt_inst2_dest_tag_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "./verilog/map_table.sv:27.19-27.28" *)
  (* wiretype = "\\TAG" *)
  input [5:0] CDB_tag_1;
  wire [5:0] CDB_tag_1;
  (* src = "./verilog/map_table.sv:27.30-27.39" *)
  (* wiretype = "\\TAG" *)
  input [5:0] CDB_tag_2;
  wire [5:0] CDB_tag_2;
  (* src = "./verilog/map_table.sv:26.19-26.30" *)
  input CDB_valid_1;
  wire CDB_valid_1;
  (* src = "./verilog/map_table.sv:26.32-26.43" *)
  input CDB_valid_2;
  wire CDB_valid_2;
  (* src = "./verilog/map_table.sv:33.17-33.30" *)
  input br_copy_valid;
  wire br_copy_valid;
  (* src = "./verilog/map_table.sv:35.17-35.33" *)
  input br_recover_valid;
  wire br_recover_valid;
  (* src = "./verilog/map_table.sv:32.35-32.53" *)
  input [2:0] br_stk_idx_copy_mt;
  wire [2:0] br_stk_idx_copy_mt;
  (* src = "./verilog/map_table.sv:34.35-34.56" *)
  input [2:0] br_stk_idx_recover_mt;
  wire [2:0] br_stk_idx_recover_mt;
  (* src = "./verilog/map_table.sv:12.17-12.22" *)
  input clock;
  wire clock;
  (* src = "./verilog/map_table.sv:23.19-23.32" *)
  input dispatch_en_1;
  wire dispatch_en_1;
  (* src = "./verilog/map_table.sv:23.34-23.47" *)
  input dispatch_en_2;
  wire dispatch_en_2;
  (* src = "./verilog/map_table.sv:30.19-30.30" *)
  input if_branch_1;
  wire if_branch_1;
  (* src = "./verilog/map_table.sv:30.32-30.43" *)
  input if_branch_2;
  wire if_branch_2;
  (* src = "./verilog/map_table.sv:45.58-45.68" *)
  wire [104:0] map_tables;
  (* src = "./verilog/map_table.sv:22.19-22.36" *)
  (* wiretype = "\\TAG" *)
  input [5:0] mt_inst1_dest_tag;
  wire [5:0] mt_inst1_dest_tag;
  (* src = "./verilog/map_table.sv:42.19-42.40" *)
  (* wiretype = "\\TAG" *)
  output [5:0] mt_inst1_dest_tag_out;
  wire [5:0] mt_inst1_dest_tag_out;
  (* src = "./verilog/map_table.sv:19.20-19.31" *)
  (* wiretype = "\\REG_IDX" *)
  input [4:0] mt_inst1_rd;
  wire [4:0] mt_inst1_rd;
  (* src = "./verilog/map_table.sv:15.20-15.32" *)
  (* wiretype = "\\REG_IDX" *)
  input [4:0] mt_inst1_rs1;
  wire [4:0] mt_inst1_rs1;
  (* src = "./verilog/map_table.sv:50.52-50.64" *)
  wire mt_inst1_rs2;
  (* src = "./verilog/map_table.sv:15.34-15.47" *)
  (* wiretype = "\\REG_IDX" *)
  input [4:0] mt_inst1_src2;
  wire [4:0] mt_inst1_src2;
  (* src = "./verilog/map_table.sv:37.21-37.44" *)
  (* wiretype = "\\TAG_PLUS" *)
  output [-1:0] mt_inst1_src_tag_plus_1;
  wire [-1:0] mt_inst1_src_tag_plus_1;
  (* src = "./verilog/map_table.sv:38.21-38.44" *)
  (* wiretype = "\\TAG_PLUS" *)
  output [-1:0] mt_inst1_src_tag_plus_2;
  wire [-1:0] mt_inst1_src_tag_plus_2;
  (* src = "./verilog/map_table.sv:22.38-22.55" *)
  (* wiretype = "\\TAG" *)
  input [5:0] mt_inst2_dest_tag;
  wire [5:0] mt_inst2_dest_tag;
  (* src = "./verilog/map_table.sv:43.19-43.40" *)
  (* wiretype = "\\TAG" *)
  output [5:0] mt_inst2_dest_tag_out;
  wire [5:0] mt_inst2_dest_tag_out;
  (* src = "./verilog/map_table.sv:19.33-19.44" *)
  (* wiretype = "\\REG_IDX" *)
  input [4:0] mt_inst2_rd;
  wire [4:0] mt_inst2_rd;
  (* src = "./verilog/map_table.sv:16.20-16.32" *)
  (* wiretype = "\\REG_IDX" *)
  input [4:0] mt_inst2_rs1;
  wire [4:0] mt_inst2_rs1;
  (* src = "./verilog/map_table.sv:16.34-16.46" *)
  (* wiretype = "\\REG_IDX" *)
  input [4:0] mt_inst2_rs2;
  wire [4:0] mt_inst2_rs2;
  (* src = "./verilog/map_table.sv:39.21-39.44" *)
  (* wiretype = "\\TAG_PLUS" *)
  output [-1:0] mt_inst2_src_tag_plus_1;
  wire [-1:0] mt_inst2_src_tag_plus_1;
  (* src = "./verilog/map_table.sv:40.21-40.44" *)
  (* wiretype = "\\TAG_PLUS" *)
  output [-1:0] mt_inst2_src_tag_plus_2;
  wire [-1:0] mt_inst2_src_tag_plus_2;
  (* src = "./verilog/map_table.sv:12.24-12.29" *)
  input reset;
  wire reset;
  assign _00_ = mt_inst2_rs2[0] & ~(mt_inst2_rs2[1]);
  assign _01_ = mt_inst2_rs2[2] ? _00_ : mt_inst2_rs2[0];
  assign _02_ = mt_inst2_rs2[3] ? _01_ : mt_inst2_rs2[0];
  assign mt_inst2_src_tag_plus_1[0] = _02_ & ~(mt_inst2_rs2[4]);
  assign _03_ = mt_inst2_rs2[1] & ~(mt_inst2_rs2[0]);
  assign _04_ = mt_inst2_rs2[2] ? _03_ : mt_inst2_rs2[1];
  assign _05_ = mt_inst2_rs2[3] ? _04_ : mt_inst2_rs2[1];
  assign mt_inst2_src_tag_plus_1[-1] = _05_ & ~(mt_inst2_rs2[4]);
  assign _06_ = mt_inst1_rs1[0] & ~(mt_inst1_rs1[1]);
  assign _07_ = mt_inst1_rs1[2] ? _06_ : mt_inst1_rs1[0];
  assign _08_ = mt_inst1_rs1[3] ? _07_ : mt_inst1_rs1[0];
  assign mt_inst1_src_tag_plus_1[0] = _08_ & ~(mt_inst1_rs1[4]);
  assign _09_ = mt_inst1_rs1[1] & ~(mt_inst1_rs1[0]);
  assign _10_ = mt_inst1_rs1[2] ? _09_ : mt_inst1_rs1[1];
  assign _11_ = mt_inst1_rs1[3] ? _10_ : mt_inst1_rs1[1];
  assign mt_inst1_src_tag_plus_1[-1] = _11_ & ~(mt_inst1_rs1[4]);
  assign _12_ = mt_inst1_rd[0] & ~(mt_inst1_rd[1]);
  assign _13_ = mt_inst1_rd[2] ? _12_ : mt_inst1_rd[0];
  assign _14_ = mt_inst1_rd[3] ? _13_ : mt_inst1_rd[0];
  assign mt_inst1_dest_tag_out[0] = _14_ & ~(mt_inst1_rd[4]);
  assign _15_ = mt_inst1_rd[1] & ~(mt_inst1_rd[0]);
  assign _16_ = mt_inst1_rd[2] ? _15_ : mt_inst1_rd[1];
  assign _17_ = mt_inst1_rd[3] ? _16_ : mt_inst1_rd[1];
  assign mt_inst1_dest_tag_out[1] = _17_ & ~(mt_inst1_rd[4]);
  assign _18_ = ~mt_inst1_rd[2];
  assign _19_ = ~(mt_inst1_rd[1] & mt_inst1_rd[0]);
  assign _20_ = ~(_19_ & mt_inst1_rd[2]);
  assign _21_ = mt_inst1_rd[3] ? _20_ : _18_;
  assign mt_inst1_dest_tag_out[2] = ~(_21_ | mt_inst1_rd[4]);
  assign _22_ = ~(_19_ | _18_);
  assign _23_ = _22_ | ~(mt_inst1_rd[3]);
  assign mt_inst1_dest_tag_out[3] = ~(_23_ | mt_inst1_rd[4]);
  assign map_tables = 105'h03868c16284880e182840608080;
  assign mt_inst1_dest_tag_out[5:4] = 2'h0;
  assign mt_inst1_rs2 = 1'hx;
  assign mt_inst1_src_tag_plus_2 = 2'hx;
  assign mt_inst2_dest_tag_out = 6'hxx;
  assign mt_inst2_src_tag_plus_2 = mt_inst2_src_tag_plus_1;
endmodule
